name: SCUS_942.36
sha1: 81cbc79f0230aeb4252e058039f47ac95a777f5a
options:
  basename: scus_942.36
  target_path: ./iso/us/SCUS_942.36
  elf_path: ./build/scus_942.36.elf
  base_path: ../../
  platform: psx
  compiler: PSYQ

  asm_path: ./asm/scus_942.36
  src_path: ./src/scus_942.36
  build_path: ./build/
  asset_path: ./assets/scus_942.36
  # create_asm_dependencies: True

  ld_script_path: ./linker/scus_942.36/scus_942.36.ld
  ld_dependencies: True

  find_file_boundaries: false
  gp_value: 0x80097FA8
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  disassemble_all: true

  section_order: [".rodata", ".text", ".data", ".sdata", ".bss", ".sbss"]
  #auto_link_sections: [".data", ".rodata", ".bss"]
  #migrate_rodata_to_functions: true

  symbol_addrs_path:
    - ./symbols/scus_942.36/symbol_addrs.txt
  reloc_addrs_path:
    - ./symbols/scus_942.36/reloc_addrs.txt

  undefined_funcs_auto_path: ./linker/scus_942.36/undefined_funcs_auto.scus_942.36.txt
  undefined_syms_auto_path: ./linker/scus_942.36/undefined_syms_auto.scus_942.36.txt

  extensions_path: ./tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: True
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x0800
    vram: 0x80010000
    # bss_size: 0x2116f
    align: 4
    subsegments:
      - [0x800, rodata]
      - [0x62D8, .rodata, psyq/libgpu]
      - [0x6714, rodata]
      - [0x6BB0, c, main/main]
      - [0x6CFC, c, main/main_loop]
      - [0x4BB8C, c, psyq/libapi]
      - [0x4BFE0, c, psyq/libc]
      - [0x4D454, c, psyq/libcard]
      - [0x4D7E8, c, psyq/libpress]
      - [0x4E2E0, c, psyq/libgpu]
      - [0x536D4, c, psyq/libgte]
      - [0x54E34, c, psyq/libcd]
      - [0x58614, c, psyq/libetc]
      - [0x5BF1C, c, psyq/libsnd]
      - [0x648D4, c, psyq/libspu]
      - [0x67638, data]
      - [0x887A8, sdata]
  - [0x88800]
